const catalogueData = [
  {
    itemName: "Watch",
    itemPrice: 20000,
    itemImage: "https://picsum.photos/seed/watch/400/300",
    itemDescription: "A stylish wrist watch for everyday use.",
    buyButton: "+",
  },
  {
    itemName: "Laptop",
    itemPrice: 650000,
    itemImage: "https://picsum.photos/seed/laptop/400/300",
    itemDescription: "A powerful laptop for work and gaming.",
    buyButton: "+",
  },
  {
    itemName: "Smartphone",
    itemPrice: 450000,
    itemImage: "https://picsum.photos/seed/smartphone/400/300",
    itemDescription: "A fast smartphone with a great camera.",
    buyButton: "+",
  },
  {
    itemName: "Headphones",
    itemPrice: 35000,
    itemImage: "https://picsum.photos/seed/headphones/400/300",
    itemDescription: "Noise-cancelling wireless headphones.",
    buyButton: "+",
  },
  {
    itemName: "Keyboard",
    itemPrice: 40000,
    itemImage: "https://picsum.photos/seed/keyboard/400/300",
    itemDescription: "Mechanical RGB gaming keyboard.",
    buyButton: "+",
  },
  {
    itemName: "Mouse",
    itemPrice: 25000,
    itemImage: "https://picsum.photos/seed/mouse/400/300",
    itemDescription: "Comfortable wireless mouse.",
    buyButton: "+",
  },
  {
    itemName: "Monitor",
    itemPrice: 180000,
    itemImage: "https://picsum.photos/seed/monitor/400/300",
    itemDescription: "24-inch Full HD display.",
    buyButton: "+",
  },
  {
    itemName: "Backpack",
    itemPrice: 30000,
    itemImage: "https://picsum.photos/seed/backpack/400/300",
    itemDescription: "Durable backpack for school or travel.",
    buyButton: "+",
  },
  {
    itemName: "Sneakers",
    itemPrice: 70000,
    itemImage: "https://picsum.photos/seed/sneakers/400/300",
    itemDescription: "Comfortable everyday sneakers.",
    buyButton: "+",
  },
  {
    itemName: "T-Shirt",
    itemPrice: 18000,
    itemImage: "https://picsum.photos/seed/tshirt/400/300",
    itemDescription: "Soft cotton T-shirt.",
    buyButton: "+",
  },
  {
    itemName: "Jeans",
    itemPrice: 45000,
    itemImage: "https://picsum.photos/seed/jeans/400/300",
    itemDescription: "Slim-fit blue jeans.",
    buyButton: "+",
  },
  {
    itemName: "Jacket",
    itemPrice: 85000,
    itemImage: "https://picsum.photos/seed/jacket/400/300",
    itemDescription: "Warm and stylish jacket.",
    buyButton: "+",
  },
  {
    itemName: "Coffee Mug",
    itemPrice: 12000,
    itemImage: "https://picsum.photos/seed/coffeemug/400/300",
    itemDescription: "Ceramic mug for coffee or tea.",
    buyButton: "+",
  },
  {
    itemName: "Water Bottle",
    itemPrice: 15000,
    itemImage: "https://picsum.photos/seed/waterbottle/400/300",
    itemDescription: "Reusable stainless steel bottle.",
    buyButton: "+",
  },
  {
    itemName: "Bluetooth Speaker",
    itemPrice: 55000,
    itemImage: "https://picsum.photos/seed/speaker/400/300",
    itemDescription: "Portable Bluetooth speaker.",
    buyButton: "+",
  },
  {
    itemName: "Power Bank",
    itemPrice: 28000,
    itemImage: "https://picsum.photos/seed/powerbank/400/300",
    itemDescription: "10000mAh portable charger.",
    buyButton: "+",
  },
  {
    itemName: "Tablet",
    itemPrice: 320000,
    itemImage: "https://picsum.photos/seed/tablet/400/300",
    itemDescription: "Lightweight tablet for entertainment.",
    buyButton: "+",
  },
  {
    itemName: "Camera",
    itemPrice: 520000,
    itemImage: "https://picsum.photos/seed/camera/400/300",
    itemDescription: "High-resolution digital camera.",
    buyButton: "+",
  },
  {
    itemName: "Gaming Chair",
    itemPrice: 150000,
    itemImage: "https://picsum.photos/seed/gamingchair/400/300",
    itemDescription: "Ergonomic chair for long gaming sessions.",
    buyButton: "+",
  },
  {
    itemName: "Desk Lamp",
    itemPrice: 22000,
    itemImage: "https://picsum.photos/seed/desklamp/400/300",
    itemDescription: "LED desk lamp with adjustable brightness.",
    buyButton: "+",
  },
  {
    itemName: "Wireless Earbuds",
    itemPrice: 45000,
    itemImage: "https://picsum.photos/seed/earbuds/400/300",
    itemDescription: "Compact true wireless earbuds.",
    buyButton: "+",
  },
  {
    itemName: "Smartwatch",
    itemPrice: 95000,
    itemImage: "https://picsum.photos/seed/smartwatch/400/300",
    itemDescription: "Fitness tracking smartwatch with heart-rate monitor.",
    buyButton: "+",
  },
  {
    itemName: "External Hard Drive",
    itemPrice: 60000,
    itemImage: "https://picsum.photos/seed/harddrive/400/300",
    itemDescription: "1TB portable external hard drive.",
    buyButton: "+",
  },
  {
    itemName: "USB Flash Drive",
    itemPrice: 8000,
    itemImage: "https://picsum.photos/seed/flashdrive/400/300",
    itemDescription: "64GB high-speed USB flash drive.",
    buyButton: "+",
  },
  {
    itemName: "Webcam",
    itemPrice: 32000,
    itemImage: "https://picsum.photos/seed/webcam/400/300",
    itemDescription: "1080p HD webcam for streaming and calls.",
    buyButton: "+",
  },
  {
    itemName: "Microphone",
    itemPrice: 48000,
    itemImage: "https://picsum.photos/seed/microphone/400/300",
    itemDescription: "USB condenser microphone for podcasting.",
    buyButton: "+",
  },
  {
    itemName: "Printer",
    itemPrice: 210000,
    itemImage: "https://picsum.photos/seed/printer/400/300",
    itemDescription: "All-in-one wireless inkjet printer.",
    buyButton: "+",
  },
  {
    itemName: "Router",
    itemPrice: 55000,
    itemImage: "https://picsum.photos/seed/router/400/300",
    itemDescription: "Dual-band Wi-Fi 6 router.",
    buyButton: "+",
  },
  {
    itemName: "Smart Bulb",
    itemPrice: 14000,
    itemImage: "https://picsum.photos/seed/smartbulb/400/300",
    itemDescription: "Color-changing smart LED bulb.",
    buyButton: "+",
  },
  {
    itemName: "Air Fryer",
    itemPrice: 130000,
    itemImage: "https://picsum.photos/seed/airfryer/400/300",
    itemDescription: "Compact digital air fryer.",
    buyButton: "+",
  },
  {
    itemName: "Blender",
    itemPrice: 65000,
    itemImage: "https://picsum.photos/seed/blender/400/300",
    itemDescription: "High-speed kitchen blender.",
    buyButton: "+",
  },
  {
    itemName: "Toaster",
    itemPrice: 38000,
    itemImage: "https://picsum.photos/seed/toaster/400/300",
    itemDescription: "2-slice stainless steel toaster.",
    buyButton: "+",
  },
  {
    itemName: "Electric Kettle",
    itemPrice: 32000,
    itemImage: "https://picsum.photos/seed/kettle/400/300",
    itemDescription: "Fast-boil electric kettle.",
    buyButton: "+",
  },
  {
    itemName: "Microwave",
    itemPrice: 145000,
    itemImage: "https://picsum.photos/seed/microwave/400/300",
    itemDescription: "Compact countertop microwave oven.",
    buyButton: "+",
  },
  {
    itemName: "Rice Cooker",
    itemPrice: 58000,
    itemImage: "https://picsum.photos/seed/ricecooker/400/300",
    itemDescription: "Automatic rice and grain cooker.",
    buyButton: "+",
  },
  {
    itemName: "Vacuum Cleaner",
    itemPrice: 175000,
    itemImage: "https://picsum.photos/seed/vacuum/400/300",
    itemDescription: "Lightweight bagless vacuum cleaner.",
    buyButton: "+",
  },
  {
    itemName: "Iron",
    itemPrice: 26000,
    itemImage: "https://picsum.photos/seed/iron/400/300",
    itemDescription: "Steam iron for clothes.",
    buyButton: "+",
  },
  {
    itemName: "Hair Dryer",
    itemPrice: 34000,
    itemImage: "https://picsum.photos/seed/hairdryer/400/300",
    itemDescription: "Compact ionic hair dryer.",
    buyButton: "+",
  },
  {
    itemName: "Electric Shaver",
    itemPrice: 42000,
    itemImage: "https://picsum.photos/seed/shaver/400/300",
    itemDescription: "Rechargeable electric shaver.",
    buyButton: "+",
  },
  {
    itemName: "Sunglasses",
    itemPrice: 25000,
    itemImage: "https://picsum.photos/seed/sunglasses/400/300",
    itemDescription: "UV-protection polarized sunglasses.",
    buyButton: "+",
  },
  {
    itemName: "Wallet",
    itemPrice: 20000,
    itemImage: "https://picsum.photos/seed/wallet/400/300",
    itemDescription: "Genuine leather bifold wallet.",
    buyButton: "+",
  },
  {
    itemName: "Belt",
    itemPrice: 15000,
    itemImage: "https://picsum.photos/seed/belt/400/300",
    itemDescription: "Classic leather belt.",
    buyButton: "+",
  },
  {
    itemName: "Cap",
    itemPrice: 10000,
    itemImage: "https://picsum.photos/seed/cap/400/300",
    itemDescription: "Adjustable cotton baseball cap.",
    buyButton: "+",
  },
  {
    itemName: "Hoodie",
    itemPrice: 38000,
    itemImage: "https://picsum.photos/seed/hoodie/400/300",
    itemDescription: "Fleece-lined pullover hoodie.",
    buyButton: "+",
  },
  {
    itemName: "Sweater",
    itemPrice: 34000,
    itemImage: "https://picsum.photos/seed/sweater/400/300",
    itemDescription: "Warm knitted sweater.",
    buyButton: "+",
  },
  {
    itemName: "Shorts",
    itemPrice: 22000,
    itemImage: "https://picsum.photos/seed/shorts/400/300",
    itemDescription: "Casual cotton shorts.",
    buyButton: "+",
  },
  {
    itemName: "Sandals",
    itemPrice: 18000,
    itemImage: "https://picsum.photos/seed/sandals/400/300",
    itemDescription: "Comfortable everyday sandals.",
    buyButton: "+",
  },
  {
    itemName: "Formal Shoes",
    itemPrice: 60000,
    itemImage: "https://picsum.photos/seed/formalshoes/400/300",
    itemDescription: "Classic leather formal shoes.",
    buyButton: "+",
  },
  {
    itemName: "Handbag",
    itemPrice: 55000,
    itemImage: "https://picsum.photos/seed/handbag/400/300",
    itemDescription: "Elegant women's handbag.",
    buyButton: "+",
  },
  {
    itemName: "Wristband",
    itemPrice: 8000,
    itemImage: "https://picsum.photos/seed/wristband/400/300",
    itemDescription: "Fitness silicone wristband.",
    buyButton: "+",
  },
  {
    itemName: "Necklace",
    itemPrice: 32000,
    itemImage: "https://picsum.photos/seed/necklace/400/300",
    itemDescription: "Stainless steel pendant necklace.",
    buyButton: "+",
  },
  {
    itemName: "Earrings",
    itemPrice: 20000,
    itemImage: "https://picsum.photos/seed/earrings/400/300",
    itemDescription: "Stylish stud earrings.",
    buyButton: "+",
  },
  {
    itemName: "Ring",
    itemPrice: 25000,
    itemImage: "https://picsum.photos/seed/ring/400/300",
    itemDescription: "Elegant stainless steel ring.",
    buyButton: "+",
  },
  {
    itemName: "Perfume",
    itemPrice: 45000,
    itemImage: "https://picsum.photos/seed/perfume/400/300",
    itemDescription: "Long-lasting eau de parfum.",
    buyButton: "+",
  },
  {
    itemName: "Body Lotion",
    itemPrice: 12000,
    itemImage: "https://picsum.photos/seed/bodylotion/400/300",
    itemDescription: "Moisturizing body lotion.",
    buyButton: "+",
  },
  {
    itemName: "Shampoo",
    itemPrice: 9000,
    itemImage: "https://picsum.photos/seed/shampoo/400/300",
    itemDescription: "Nourishing hair shampoo.",
    buyButton: "+",
  },
  {
    itemName: "Toothbrush Set",
    itemPrice: 6000,
    itemImage: "https://picsum.photos/seed/toothbrush/400/300",
    itemDescription: "Electric toothbrush with two heads.",
    buyButton: "+",
  },
  {
    itemName: "Sunscreen",
    itemPrice: 11000,
    itemImage: "https://picsum.photos/seed/sunscreen/400/300",
    itemDescription: "SPF 50 broad-spectrum sunscreen.",
    buyButton: "+",
  },
  {
    itemName: "Yoga Mat",
    itemPrice: 24000,
    itemImage: "https://picsum.photos/seed/yogamat/400/300",
    itemDescription: "Non-slip exercise yoga mat.",
    buyButton: "+",
  },
  {
    itemName: "Dumbbells Set",
    itemPrice: 65000,
    itemImage: "https://picsum.photos/seed/dumbbells/400/300",
    itemDescription: "Adjustable dumbbells set.",
    buyButton: "+",
  },
  {
    itemName: "Resistance Bands",
    itemPrice: 15000,
    itemImage: "https://picsum.photos/seed/bands/400/300",
    itemDescription: "Set of 5 resistance bands.",
    buyButton: "+",
  },
  {
    itemName: "Jump Rope",
    itemPrice: 8000,
    itemImage: "https://picsum.photos/seed/jumprope/400/300",
    itemDescription: "Adjustable speed jump rope.",
    buyButton: "+",
  },
  {
    itemName: "Football",
    itemPrice: 22000,
    itemImage: "https://picsum.photos/seed/football/400/300",
    itemDescription: "Standard size 5 football.",
    buyButton: "+",
  },
  {
    itemName: "Basketball",
    itemPrice: 25000,
    itemImage: "https://picsum.photos/seed/basketball/400/300",
    itemDescription: "Official size basketball.",
    buyButton: "+",
  },
  {
    itemName: "Tennis Racket",
    itemPrice: 48000,
    itemImage: "https://picsum.photos/seed/tennisracket/400/300",
    itemDescription: "Lightweight aluminum tennis racket.",
    buyButton: "+",
  },
  {
    itemName: "Bicycle",
    itemPrice: 320000,
    itemImage: "https://picsum.photos/seed/bicycle/400/300",
    itemDescription: "Mountain bike with 21-speed gears.",
    buyButton: "+",
  },
  {
    itemName: "Helmet",
    itemPrice: 35000,
    itemImage: "https://picsum.photos/seed/helmet/400/300",
    itemDescription: "Protective cycling helmet.",
    buyButton: "+",
  },
  {
    itemName: "Skateboard",
    itemPrice: 42000,
    itemImage: "https://picsum.photos/seed/skateboard/400/300",
    itemDescription: "Complete maple deck skateboard.",
    buyButton: "+",
  },
  {
    itemName: "Fishing Rod",
    itemPrice: 38000,
    itemImage: "https://picsum.photos/seed/fishingrod/400/300",
    itemDescription: "Telescopic carbon fiber fishing rod.",
    buyButton: "+",
  },
  {
    itemName: "Tent",
    itemPrice: 95000,
    itemImage: "https://picsum.photos/seed/tent/400/300",
    itemDescription: "2-person waterproof camping tent.",
    buyButton: "+",
  },
  {
    itemName: "Sleeping Bag",
    itemPrice: 45000,
    itemImage: "https://picsum.photos/seed/sleepingbag/400/300",
    itemDescription: "Warm outdoor sleeping bag.",
    buyButton: "+",
  },
  {
    itemName: "Flashlight",
    itemPrice: 14000,
    itemImage: "https://picsum.photos/seed/flashlight/400/300",
    itemDescription: "Rechargeable LED flashlight.",
    buyButton: "+",
  },
  {
    itemName: "Cooler Box",
    itemPrice: 38000,
    itemImage: "https://picsum.photos/seed/coolerbox/400/300",
    itemDescription: "Insulated portable cooler box.",
    buyButton: "+",
  },
  {
    itemName: "Board Game",
    itemPrice: 28000,
    itemImage: "https://picsum.photos/seed/boardgame/400/300",
    itemDescription: "Family strategy board game.",
    buyButton: "+",
  },
  {
    itemName: "Puzzle Set",
    itemPrice: 12000,
    itemImage: "https://picsum.photos/seed/puzzle/400/300",
    itemDescription: "1000-piece jigsaw puzzle.",
    buyButton: "+",
  },
  {
    itemName: "Action Figure",
    itemPrice: 18000,
    itemImage: "https://picsum.photos/seed/actionfigure/400/300",
    itemDescription: "Collectible action figure.",
    buyButton: "+",
  },
  {
    itemName: "Remote Control Car",
    itemPrice: 35000,
    itemImage: "https://picsum.photos/seed/rccar/400/300",
    itemDescription: "High-speed remote control car.",
    buyButton: "+",
  },
  {
    itemName: "Building Blocks Set",
    itemPrice: 30000,
    itemImage: "https://picsum.photos/seed/blocks/400/300",
    itemDescription: "Creative building blocks set.",
    buyButton: "+",
  },
  {
    itemName: "Baby Stroller",
    itemPrice: 165000,
    itemImage: "https://picsum.photos/seed/stroller/400/300",
    itemDescription: "Lightweight foldable baby stroller.",
    buyButton: "+",
  },
  {
    itemName: "Diaper Bag",
    itemPrice: 32000,
    itemImage: "https://picsum.photos/seed/diaperbag/400/300",
    itemDescription: "Multi-pocket diaper bag.",
    buyButton: "+",
  },
  {
    itemName: "Baby Bottle Set",
    itemPrice: 15000,
    itemImage: "https://picsum.photos/seed/babybottle/400/300",
    itemDescription: "Anti-colic baby bottle set.",
    buyButton: "+",
  },
  {
    itemName: "Office Chair",
    itemPrice: 120000,
    itemImage: "https://picsum.photos/seed/officechair/400/300",
    itemDescription: "Ergonomic mesh office chair.",
    buyButton: "+",
  },
  {
    itemName: "Study Desk",
    itemPrice: 95000,
    itemImage: "https://picsum.photos/seed/studydesk/400/300",
    itemDescription: "Compact wooden study desk.",
    buyButton: "+",
  },
  {
    itemName: "Bookshelf",
    itemPrice: 85000,
    itemImage: "https://picsum.photos/seed/bookshelf/400/300",
    itemDescription: "5-tier wooden bookshelf.",
    buyButton: "+",
  },
  {
    itemName: "Wall Clock",
    itemPrice: 18000,
    itemImage: "https://picsum.photos/seed/wallclock/400/300",
    itemDescription: "Modern minimalist wall clock.",
    buyButton: "+",
  },
  {
    itemName: "Photo Frame",
    itemPrice: 9000,
    itemImage: "https://picsum.photos/seed/photoframe/400/300",
    itemDescription: "Wooden picture photo frame.",
    buyButton: "+",
  },
  {
    itemName: "Curtains",
    itemPrice: 35000,
    itemImage: "https://picsum.photos/seed/curtains/400/300",
    itemDescription: "Blackout window curtains, pair.",
    buyButton: "+",
  },
  {
    itemName: "Bed Sheet Set",
    itemPrice: 28000,
    itemImage: "https://picsum.photos/seed/bedsheet/400/300",
    itemDescription: "Soft cotton bed sheet set.",
    buyButton: "+",
  },
  {
    itemName: "Pillow",
    itemPrice: 14000,
    itemImage: "https://picsum.photos/seed/pillow/400/300",
    itemDescription: "Memory foam bed pillow.",
    buyButton: "+",
  },
  {
    itemName: "Blanket",
    itemPrice: 32000,
    itemImage: "https://picsum.photos/seed/blanket/400/300",
    itemDescription: "Warm fleece throw blanket.",
    buyButton: "+",
  },
  {
    itemName: "Cookware Set",
    itemPrice: 110000,
    itemImage: "https://picsum.photos/seed/cookware/400/300",
    itemDescription: "10-piece non-stick cookware set.",
    buyButton: "+",
  },
  {
    itemName: "Cutlery Set",
    itemPrice: 38000,
    itemImage: "https://picsum.photos/seed/cutlery/400/300",
    itemDescription: "Stainless steel cutlery set.",
    buyButton: "+",
  },
  {
    itemName: "Dinner Plate Set",
    itemPrice: 42000,
    itemImage: "https://picsum.photos/seed/dinnerplate/400/300",
    itemDescription: "12-piece ceramic dinner plate set.",
    buyButton: "+",
  },
  {
    itemName: "Knife Set",
    itemPrice: 45000,
    itemImage: "https://picsum.photos/seed/knifeset/400/300",
    itemDescription: "Professional kitchen knife set.",
    buyButton: "+",
  },
  {
    itemName: "Storage Boxes",
    itemPrice: 22000,
    itemImage: "https://picsum.photos/seed/storagebox/400/300",
    itemDescription: "Set of 3 stackable storage boxes.",
    buyButton: "+",
  },
  {
    itemName: "Umbrella",
    itemPrice: 16000,
    itemImage: "https://picsum.photos/seed/umbrella/400/300",
    itemDescription: "Windproof folding umbrella.",
    buyButton: "+",
  },
  {
    itemName: "Travel Bag",
    itemPrice: 68000,
    itemImage: "https://picsum.photos/seed/travelbag/400/300",
    itemDescription: "Large capacity travel duffel bag.",
    buyButton: "+",
  },
  {
    itemName: "Suitcase",
    itemPrice: 95000,
    itemImage: "https://picsum.photos/seed/suitcase/400/300",
    itemDescription: "Hard-shell 24-inch suitcase.",
    buyButton: "+",
  },
  {
    itemName: "Passport Holder",
    itemPrice: 12000,
    itemImage: "https://picsum.photos/seed/passportholder/400/300",
    itemDescription: "Leather passport holder with card slots.",
    buyButton: "+",
  },
  {
    itemName: "Neck Pillow",
    itemPrice: 10000,
    itemImage: "https://picsum.photos/seed/neckpillow/400/300",
    itemDescription: "Travel memory foam neck pillow.",
    buyButton: "+",
  },
  {
    itemName: "Portable Charger Fan",
    itemPrice: 18000,
    itemImage: "https://picsum.photos/seed/handfan/400/300",
    itemDescription: "Rechargeable handheld mini fan.",
    buyButton: "+",
  }
];

export { catalogueData };